apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - namespaces.yaml
 - rabbitmq.yaml
 - web.yaml
 - worker.yaml
 - mimir.yaml

configMapGenerator:
  - name: alloy-config
    namespace: monitoring
    files:
      - configs/config.alloy

  - name: mimir-config
    namespace: monitoring
    files:
      - configs/mimir.yaml

  - name: celery-dashboard
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - configs/dashboards/celery.json

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    releaseName: alloy
    namespace: monitoring
    valuesFile: values-alloy.yaml

  - name: loki
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: monitoring
    valuesFile: values-loki.yaml

  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: monitoring
    valuesFile: values-grafana.yaml

  - name: kube-state-metrics
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-state-metrics
    namespace: monitoring
    valuesFile: values-ksm.yaml
