apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - namespaces.yaml
 - rabbitmq.yaml
 - web.yaml
 - worker.yaml

configMapGenerator:
  - name: alloy-config
    namespace: monitoring
    files:
      - configs/config.alloy

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    releaseName: alloy
    namespace: monitoring
    valuesFile: values-alloy.yaml

  - name: loki
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: monitoring
    valuesFile: values-loki.yaml

  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: monitoring
    valuesFile: values-grafana.yaml
