adminUser: admin
adminPassword: password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: false
    - name: mimir
      type: prometheus
      uid: mimir
      access: proxy
      url: http://mimir-service:8080/prometheus
      isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: celery-dashboard

testFramework:
  enabled: false

persistence:
  enabled: false
