alloy:
  mounts:
    varlog: true

  configMap:
    content: |-
      discovery.kubernetes "pods" {
        role = "pod"

        selectors {
          role = "pod"
          field = "spec.nodeName=" + sys.env("HOSTNAME")
        }
      }

      discovery.relabel "pod_logs" {
        targets = discovery.kubernetes.pods.targets

          rule {
            source_labels = ["__meta_kubernetes_namespace"]
            action = "replace"
            target_label = "namespace"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_name"]
            action = "replace"
            target_label = "pod"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_container_name"]
            action = "replace"
            target_label = "container"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_label_app"]
            action = "replace"
            target_label = "app"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
            separator = "/"
            action = "replace"
            replacement = "/var/log/pods/*$1/*.log"
            target_label = "__path__"
          }
      }

      local.file_match "pod_logs" {
        path_targets = discovery.relabel.pod_logs.output
      }
