apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject
  namespace: app
  labels:
    app: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      volumes:
      - name: tmp-database
        emptyDir: {}
      containers:
      - name: myproject
        image: celery-app:latest
        imagePullPolicy: Never
        command: ["python3", "main.py"]
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - mountPath: /data
          name: tmp-database
        env:
        - name: DATABASE_DIR
          value: /data
        - name: CELERY_BROKER_URL
          value: "amqp://guest:guest@rabbitmq-service:5672"
        - name: CELERY_RESULT_BACKEND
          value: "rpc://"
---
apiVersion: v1
kind: Service
metadata:
  name: myproject-service
  namespace: app
spec:
  selector:
    app: myproject
  ports:
  - port: 5000
    targetPort: 5000
    name: http
